### ISSUE TITLE
Do we still need nightly?

### ISSUE THREAD

**Issue by JulianKniephoff** [JulianKniephoff/snek#13]

**Comment by LukasKalbertodt** [comment]
`snek` itself just uses `box_syntax` which is only for convenience. And the `nightly` feature of `wasm-bindgen` apparently only enables the `Closure::new` function. But I think `Closure::wrap` should work in almost all cases too.

**Comment by JulianKniephoff** [comment]
Since I like living on the edge, and this is not in any way "essential" software or anything, I'll just make the executive decision to not care about this anymore. `snek` will probably stay on nightly indefinitely, and consequently this issue can be closed.
